<?php

/**
 * QuizQuestionAnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizQuestionAnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizQuestionAnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuizQuestionAnswers');
    }
}