<?php

/**
 * QuizQuestionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuizQuestionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuizQuestionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuizQuestions');
    }
}