<?php

/**
 * StudentsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Students');
    }
}