<?php

/**
 * StudentQuestionsAnswersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentQuestionsAnswersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentQuestionsAnswersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentQuestionsAnswers');
    }
}