<?php

/**
 * StudentQuizzesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentQuizzesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentQuizzesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentQuizzes');
    }
}